AllCops:
  Exclude:
      - 'vendor/**/*'
      - 'test/fixtures/**/*'
      - 'tmp/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 150

Style/CaseEquality:
  Exclude:
    - 'test/**/*'

Style/AsciiComments:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'test/**/*'

